[package]
name = "solcore-nameres"
version = "0.1.0"
edition.workspace = true

[dependencies]
salsa = { workspace = true }
rustc-hash = { workspace = true }
url = { workspace = true }
hir = { workspace = true }
parser = { workspace = true }

[dev-dependencies]
annotate-snippets = { workspace = true }
insta = "1.43.2"
