[package]
name = "solcore-hir"
version = "0.1.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
salsa = { workspace = true }
annotate-snippets = { workspace = true }
percent-encoding = { workspace = true }
rustc-hash = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
