[package]
name = "solcore-driver"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
annotate-snippets = { workspace = true }
libc = "0.2"
salsa = { workspace = true }
rustc-hash = { workspace = true }
url = { workspace = true }
hir = { workspace = true }
hir-ty = { workspace = true }
hull = { path = "../hull", package = "solcore-hull" }
parser = { workspace = true }
nameres = { workspace = true }
specialize = { path = "../specialize", package = "solcore-specialize" }
sonatina = { path = "../sonatina", package = "solcore-sonatina" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
yul = { path = "../yul", package = "solcore-yul" }
