[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
salsa = "0.25"
url = "2.5"
annotate-snippets = "0.12"
parser = { path = "crates/parser", package = "solcore-parser" }
parser2 = { path = "crates/parser2", package = "solcore-parser2" }
hull = { path = "crates/hull", package = "solcore-hull" }

[workspace.package]
edition = "2024"
