[package]
name = "solcore-yul"
version = "0.1.0"
edition.workspace = true

[dependencies]
hir = { workspace = true }
hull = { path = "../hull", package = "solcore-hull" }

[dev-dependencies]
dir-test = "0.4.1"
hir-ty = { workspace = true }
insta = "1.43.2"
nameres = { workspace = true }
parser = { workspace = true }
rustc-hash = { workspace = true }
salsa = { workspace = true }
solcore-test-utils = { path = "../test-utils" }
specialize = { path = "../specialize", package = "solcore-specialize" }
url = { workspace = true }
