[package]
name = "solcore-uitest"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
hir = { workspace = true }
hir-ty = { workspace = true }
hull = { path = "../hull", package = "solcore-hull" }
nameres = { workspace = true }
parser = { workspace = true }
salsa = { workspace = true }
solcore-test-utils = { path = "../test-utils" }
specialize = { path = "../specialize", package = "solcore-specialize" }

[dev-dependencies]
dir-test = "0.4.1"
