import { Binary, ChevronDown, Hammer, Loader2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useWorkspaceStore } from "../store/workspace";
import { CopyButton } from "./CopyButton";

export function CompileControl(): JSX.Element {
  const result = useWorkspaceStore((s) => s.lastCompiledVersion === s.workspaceVersion ? s.result : null);
  const compiling = useWorkspaceStore((s) => s.compiling);
  const running = useWorkspaceStore((s) => s.running);
  const compile = useWorkspaceStore((s) => s.compileNow);
  const compiled = Boolean(result?.success);
  const label = compiling && !running ? "Compiling…" : compiled ? "Compiled" : "Compile";
  const [objectName, setObjectName] = useState("");
  const [sectionName, setSectionName] = useState("init");
  const menu = useRef<HTMLDetailsElement>(null);
  const objects = result?.bytecode ?? [];
  const object = objects.find((item) => item.name === objectName) ?? objects[0];
  const section = object?.sections.find((item) => item.name === sectionName) ?? object?.sections[0];

  const placePanel = () => {
    const root = menu.current;
    const panel = root?.querySelector<HTMLElement>(".bytecode-menu__panel");
    if (!root?.open || !panel) return;
    const anchor = root.getBoundingClientRect();
    const left = Math.max(8, Math.min(anchor.left, window.innerWidth - panel.offsetWidth - 8));
    panel.style.left = `${left - anchor.left}px`;
  };

  useEffect(() => {
    const dismiss = (event: PointerEvent) => {
      if (menu.current && event.target instanceof Node && !menu.current.contains(event.target)) menu.current.open = false;
    };
    const escape = (event: KeyboardEvent) => {
      if (event.key === "Escape" && menu.current?.open) {
        menu.current.open = false;
        menu.current.querySelector("summary")?.focus();
      }
    };
    window.addEventListener("resize", placePanel);
    document.addEventListener("pointerdown", dismiss);
    document.addEventListener("keydown", escape);
    return () => {
      window.removeEventListener("resize", placePanel);
      document.removeEventListener("pointerdown", dismiss);
      document.removeEventListener("keydown", escape);
    };
  }, []);

  return <details className="bytecode-menu" ref={menu} onToggle={placePanel}>
    <summary className="button button--secondary" aria-label={label} aria-disabled={compiling}
      title={compiled ? "View and copy compiled bytecode" : "Compile"}
      onClick={(event) => {
        if (compiling) { event.preventDefault(); return; }
        if (!compiled) {
          event.preventDefault();
          void compile();
        }
      }}>
      {compiling && !running ? <Loader2 className="spin" size={16} aria-hidden="true" /> : compiled ? <Binary size={16} aria-hidden="true" /> : <Hammer size={16} aria-hidden="true" />}
      <span>{label}</span>{compiled ? <ChevronDown size={14} aria-hidden="true" /> : null}
    </summary>
    <div className="bytecode-menu__panel">
      <h2>Bytecode</h2>
      {object && section ? <>
        <div className="bytecode-toolbar">
          <label>Object <select aria-label="Bytecode object" value={object.name} onChange={(event) => setObjectName(event.target.value)}>
            {objects.map((item) => <option key={item.name}>{item.name}</option>)}
          </select></label>
          <label>Section <select aria-label="Bytecode section" value={section.name} onChange={(event) => setSectionName(event.target.value)}>
            {object.sections.map((item) => <option key={item.name} value={item.name}>
              {item.name === "init" ? "Creation" : item.name === "runtime" ? "Runtime" : item.name}
            </option>)}
          </select></label>
        </div>
        <pre tabIndex={0} role="region" className="bytecode-menu__code" aria-label="Generated bytecode">{section.code}</pre>
        <div className="bytecode-toolbar">
          <span>{(section.code.length - 2) / 2} bytes</span>
          <CopyButton label="Copy bytecode" showLabel text={section.code} />
        </div>
        {section.name === "init" ? <p className="bytecode-note">Constructor arguments are not included.</p> : null}
      </> : <p className="bytecode-note">Compile to generate bytecode.</p>}
    </div>
  </details>;
}
