[package]
name = "solcore-hir-ty"
version = "0.1.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ena = { workspace = true }
hir = { workspace = true }
matchcov = { workspace = true }
nameres = { workspace = true }
num-bigint = { workspace = true }
parser = { workspace = true }
rustc-hash = { workspace = true }
salsa = { workspace = true }
tablesolve = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
dir-test = "0.4.1"
proptest = { workspace = true }
solcore-test-utils = { path = "../test-utils" }
url = { workspace = true }
